spring:
  application:
    name=blps_lab

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres 


  jpa:
    hibernate:
      ddl-auto: none

    defer-datasource-initialization: true

  sql:
    init:
      mode: always